version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      mysql:
        condition: service_healthy  # ✅ Wait for MySQL to be healthy
    networks:
      - laravel
    ports:
      - "9000:9000"

  web:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager      # ✅ corrected spelling
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:                      # ✅ ensure Laravel waits for MySQL
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
